### PR TITLE
Nerd Pack: Code refactoring, bug fixes and improvements

### PR DESCRIPTION
**Pull request by eschultz**
With the exception of a few bugs fixes and improvements in this pull request, Nerd Pack will work the same as it has.  

I was originally planning to merge your Nerd Pack interface in to my github repo but, if it's ok with you, I'd rather just move Nerd Pack (packages and all) to your repo, update my plg link to your repo, and EOL mine.  I can still help you maintain the code and packages -- It'll just be in the form of pull requests.  Would you be open to this or you have any other thoughts about it?

Here are some of the bug fixes in this PR:
- Fixed first time running warnings about missing packages.json / desc files
- Fixed bug preventing Select All from being toggle-able 
- Fixed bug in Select All and dependent package checkboxes / race condition
- Eliminated vertical space gap between page header and table

### CODE REVIEW

**Comment by dmacias72** [comment]
I really appreciate you taking the time to go through this and clean it up. I don't mind moving it all over to this repo.  It wasn't my intention to take it over though. I would like any help you can give to code and packages. I don't know if you compiled all or any of the packages but I'm not really setup to compile any right now.

**Comment by dmacias72** [comment]
I noticed you moved the tablesorter out of packageQuery().  I originally had it in the document ready function but couldn't get saved filters to work. Does it cause a problem calling it within packageQuery()?

**Comment by eschultz** [comment]
I moved the tablesorter (initialization) to the first thing in document ready (above the switchbuttons) to fix the issue of being able to toggle the 'Select All'.  The saved filters are still working for me though, did it break for you?

**Comment by eschultz** [comment]
oh, the 'live search' is persisting across page refreshes but the filter dropdowns (by status, by download, by install) are not...  I'll look in to this.

**Comment by dmacias72** [comment]
I see what you mean about the 'check all' being broke. I didn't notice that when I moved tablesorter. If I move tablesorter and 'check all' to packageQuery() it works.  Do you see a problem with that?

**Comment by dmacias72** [comment]
One thing that could be misleading is a 'check all' on a filtered table will check everything.

**Comment by eschultz** [comment]
Alrighty, I was able to fix both those issues.  For some reason `$("#tblPackages").trigger("update");` is resetting the saved filters and I was able to get around it by saving the filter state to variable right before 'update' is triggered and then restore the filter state after.  I didn't move the tablesorter init block back in to packageQuery() because it's really only meant to be setup/called once with that constructor.

I updated the 'Select All' to only toggle the visible packages (based on your current filters).

Want me to submit another pull request with these updates?

**Comment by dmacias72** [comment]
Yes thank you. I wonder if that's a bug with tablsorter.

**Pull request merged**
